### ISSUE TITLE
kernelreport.sh: Control which kernel changes are used for comparison 

### ISSUE THREAD

**Issue by sumitsemwal** [Linaro/android-report#21]
Currently, for any project, kernelreport.sh only compares 2 kernels if their minor version is different. This was done to reduce the number of reports that can get generated.
However, for some of the currently active kernels, we may want to generate reports even if the minor version is the same, and more patches are added to the kernel.
Investigate if adding such a control would be easy to add.

**Comment by liuyq** [comment]
@sumitsemwal are you OK to have this issue closed now?

**Comment by sumitsemwal** [comment]
Yes, please. Thanks very much!
