### ISSUE TITLE
kernelreport.sh: allow comparison of two builds with their sha IDs as well

### ISSUE THREAD

**Issue by sumitsemwal** [Linaro/android-report#31]
if there are more than 2 builds for the same extra version (5.10.42-aaa, 5.10.42-bbb, 5.10.42-ccc), currently the kernelreport.sh doesn't properly allow comparison of any 2 of these - it only picks up the latest and compares with the previous one.
To allow comparison of any 2, we need a mechanism to compare any two given builds. Please could you add this as a feature?

**Comment by liuyq** [comment]
@sumitsemwal are you OK to have this issue closed now?

**Comment by sumitsemwal** [comment]
Hi Yongqin,

Yes, this could be closed now, please.

Best,
Sumit.
